function log () {
    console.log('1')
    console.log('1')
    console.log('1')
    console.log('1')
    console.log('1')
    console.log('1')
    console.log('1')
    console.log('1')
    console.log('1')
    console.log('1')
    console.log('1')
    console.log('1')
    console.log('1')
    console.log('1')
}
log()
console.log('salam')